[package]
name = "bec_broadcast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tweet_nacl_rust = { path = "../tweet_nacl_rust"}
sha2 = "0.10.2"